---
- name: Set permissions on snapcenter directories
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0750'
    group: nginx
    state: directory
  loop:
    - "{{ snapcenter_runtime_dir }}"
    - "{{ snapcenter_certs_dir }}"

- name: Set permissions on SSL certificates
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0640'
    group: nginx
  loop:
    - "{{ snapcenter_cert_file }}"
    - "{{ snapcenter_key_file }}"

- name: Set SELinux context for certificates
  ansible.posix.sefcontext:
    target: "{{ snapcenter_certs_dir }}(/.*)?"
    setype: cert_t
    state: present

- name: Restore SELinux context for certificates
  ansible.builtin.command: "restorecon -Rv {{ snapcenter_certs_dir }}"
  register: restorecon_certs
  changed_when: restorecon_certs.stdout != ""

- name: Allow nginx to connect to backend services
  ansible.posix.seboolean:
    name: httpd_can_network_connect
    state: true
    persistent: true

- name: Disable client certificate requirement in nginx
  ansible.builtin.replace:
    path: "{{ snapcenter_nginx_conf }}"
    regexp: 'ssl_verify_client optional_no_ca;'
    replace: 'ssl_verify_client off;'

- name: Restart nginx to apply configuration
  ansible.builtin.systemd:
    name: nginx
    state: restarted