---
- name: Install SnapCenter Linux server
  ansible.builtin.command: >
    {{ snapcenter_tmp_dir }}/{{ snapcenter_binary }} -i silent
    {{ snapcenter_install_args | join(' ') }}
  args:
    creates: /etc/nginx/conf.d/snapcenter.conf
  become: true
  become_user: root
  become_flags: '-i'
  register: snapcenter_install_result
  notify: Wait for snapcenter services
