---
- name: Install SnapCenter Linux server
  ansible.builtin.command: >
    {{ snapcenter_tmp_dir }}/{{ snapcenter_binary }} -i silent
    {{ snapcenter_install_args | join(' ') }}
  args:
    creates: "{{ snapcenter_install_dir }}"
  become: true
  register: snapcenter_install_result
  notify: Wait for snapcenter services
