---
- name: Create Linux admin account
  ansible.builtin.user:
    name: admin
    password: "{{ vault_admin_password | password_hash('sha512') }}"
    update_password: on_create
    state: present
    create_home: false
    shell: /sbin/nologin

- name: Create Linux user accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    password: "{{ item.password | password_hash('sha512') }}"
    update_password: on_create
    state: present
    create_home: false
    shell: /sbin/nologin
  loop: "{{ vault_snapcenter_users | default([]) }}"
  when: vault_snapcenter_users is defined
  no_log: true
