---
- name: 1/4 Pre-check Inputs
  ansible.builtin.include_tasks: 1_pre-check_inputs.yml

- name: 2/4 Create Linux Accounts
  ansible.builtin.include_tasks: 2_linux_users.yml

- name: 3/4 SnapCenter API - Authenticate & Get Token
  ansible.builtin.include_tasks: 3_sc_api_auth.yml

- name: 4/4 Create SnapCenter Users & Assign Roles
  ansible.builtin.include_tasks: 4_sc_user_create.yml
