---
- name: Delete users from SnapCenter
  ansible.builtin.uri:
    url: "https://localhost:{{ snapcenter_webapp_port }}/api/{{ snapcenter_api_version }}/User?UserNames={{ item }}"
    method: DELETE
    headers:
      Token: "{{ snapcenter_update_users_auth_token }}"
      Content-Type: application/json
    validate_certs: false
    status_code: [200]
  loop: "{{ snapcenter_update_users_to_delete }}"
  loop_control:
    label: "{{ item }}"
  register: snapcenter_update_users_delete_api_results
  failed_when: >-
    ('json' in snapcenter_update_users_delete_api_results
      and snapcenter_update_users_delete_api_results.json.Result._errorCode | default(-1) != 0)

- name: Delete Linux accounts for removed users
  ansible.builtin.user:
    name: "{{ item }}"
    state: absent
    remove: true
    force: true
  loop: "{{ snapcenter_update_users_to_delete }}"
  loop_control:
    label: "{{ item }}"
